# Generated by Django 5.2.6 on 2025-09-25 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='translation',
            name='browser_info',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='translation',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
