# Generated by Django 5.2.6 on 2025-09-30 03:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BagType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('browser_info', models.CharField(blank=True, max_length=255, null=True)),
                ('session', models.IntegerField(choices=[(2020, '2020'), (2021, '2021'), (2022, '2022'), (2023, '2023'), (2024, '2024'), (2025, '2025'), (2026, '2026'), (2027, '2027'), (2028, '2028'), (2029, '2029'), (2030, '2030'), (2031, '2031'), (2032, '2032'), (2033, '2033'), (2034, '2034')], default=2025)),
                ('name', models.CharField(max_length=255)),
                ('per_bag_rent', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('per_kg_rent', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('agent_bag_rent', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('agent_kg_rent', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('party_bag_rent', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('party_kg_rent', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('per_bag_loan', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('empty_bag_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fan_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
