# Generated by Django 4.2.15 on 2025-10-04 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('essential_settings', '0003_transactionsetting_generalsetting_basicsetting'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basicsetting',
            options={},
        ),
        migrations.AlterModelOptions(
            name='generalsetting',
            options={},
        ),
        migrations.AlterModelOptions(
            name='transactionsetting',
            options={},
        ),
        migrations.AlterModelTable(
            name='basicsetting',
            table=None,
        ),
        migrations.AlterModelTable(
            name='generalsetting',
            table=None,
        ),
        migrations.AlterModelTable(
            name='transactionsetting',
            table=None,
        ),
    ]
