# Generated by Django 4.2.15 on 2025-10-04 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essential_settings', '0004_alter_basicsetting_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalsetting',
            name='key',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
    ]
