# Generated by Django 5.2.6 on 2025-10-05 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essential_settings', '0005_alter_generalsetting_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicsetting',
            name='delivery_type',
            field=models.CharField(choices=[('bag', 'Bag'), ('kg', 'Kg')], default='bag', max_length=16),
        ),
        migrations.AlterField(
            model_name='basicsetting',
            name='value_mode',
            field=models.CharField(choices=[('floor', 'Floor'), ('round', 'Round'), ('ceil', 'Ceil')], default='floor', max_length=16),
        ),
    ]
