# Generated by Django 4.2.15 on 2025-09-21 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsizesetting',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.category'),
        ),
        migrations.AddField(
            model_name='productsizesetting',
            name='code',
            field=models.BigIntegerField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='productsizesetting',
            name='product',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='size_settings', to='products.product'),
        ),
        migrations.AlterField(
            model_name='productsizesetting',
            name='size',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.unitsize'),
        ),
        migrations.AlterField(
            model_name='productsizesetting',
            name='unit',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.unit'),
        ),
    ]
