# Generated by Django 4.2.15 on 2025-09-21 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesstype',
            name='business_type',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_business_type', to='company.businesstype'),
        ),
        migrations.AddField(
            model_name='businesstype',
            name='factory',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_factory', to='company.factory'),
        ),
        migrations.AddField(
            model_name='company',
            name='business_type',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_business_type', to='company.businesstype'),
        ),
        migrations.AddField(
            model_name='company',
            name='company',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_company', to='company.company'),
        ),
        migrations.AddField(
            model_name='company',
            name='factory',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_factory', to='company.factory'),
        ),
        migrations.AddField(
            model_name='factory',
            name='factory',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_factory', to='company.factory'),
        ),
    ]
