# Generated by Django 4.2.15 on 2025-09-21 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_businesstype_business_type_businesstype_factory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businesstype',
            name='business_type',
        ),
        migrations.RemoveField(
            model_name='businesstype',
            name='factory',
        ),
        migrations.RemoveField(
            model_name='company',
            name='business_type',
        ),
        migrations.RemoveField(
            model_name='company',
            name='company',
        ),
        migrations.RemoveField(
            model_name='company',
            name='factory',
        ),
        migrations.RemoveField(
            model_name='factory',
            name='factory',
        ),
    ]
