# Generated by Django 5.2.6 on 2025-09-25 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_remove_businesstype_business_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesstype',
            name='browser_info',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='businesstype',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='browser_info',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='factory',
            name='browser_info',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='factory',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
