# Generated by Django 4.2.15 on 2025-09-24 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_remove_businesstype_business_type_and_more'),
        ('party_type', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partytype',
            name='company',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='parties', to='company.company'),
        ),
    ]
