# Generated by Django 5.2.6 on 2025-09-25 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party_type', '0002_partytype_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='code',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
