# Generated by Django 4.2.15 on 2025-10-04 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_businesstype_deleted_at_businesstype_deleted_by_and_more'),
        ('party_type', '0003_party_deleted_at_party_deleted_by_party_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partytype',
            name='company',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='party-type', to='company.company'),
        ),
    ]
