# Generated by Django 5.2.6 on 2025-09-25 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party_type', '0003_alter_party_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='browser_info',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='party',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partytype',
            name='browser_info',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='partytype',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
