# Generated by Django 4.2.15 on 2025-09-26 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('party_type', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('browser_info', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateField()),
                ('sr_no', models.PositiveIntegerField(unique=True)),
                ('customer_name', models.CharField(max_length=255)),
                ('father_name', models.CharField(blank=True, max_length=255, null=True)),
                ('village', models.CharField(blank=True, max_length=255, null=True)),
                ('post', models.CharField(blank=True, max_length=255, null=True)),
                ('thana', models.CharField(blank=True, max_length=255, null=True)),
                ('zila', models.CharField(blank=True, max_length=255, null=True)),
                ('mobile', models.CharField(blank=True, max_length=30, null=True)),
                ('nid', models.CharField(blank=True, max_length=50, null=True)),
                ('bag_type', models.CharField(max_length=200)),
                ('lot_number', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('submitted_bag_quantity', models.PositiveIntegerField(default=0)),
                ('bag_rent', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('total_rent', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('labour_charge', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
                ('party', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='party_srs', to='party_type.party')),
                ('product_type', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='sr_products', to='products.producttype')),
            ],
            options={
                'ordering': ['sr_no'],
            },
        ),
    ]
