# Generated by Django 5.2.6 on 2025-09-25 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sr',
            name='lot_number',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
