# Generated by Django 5.2.6 on 2025-09-18 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermissionset',
            name='accounts_module',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='userpermissionset',
            name='company_module',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='userpermissionset',
            name='hr_module',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='userpermissionset',
            name='inventory_module',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='userpermissionset',
            name='product_module',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='userpermissionset',
            name='settings_module',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
