# Generated by Django 4.2.15 on 2025-09-24 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermissionset',
            name='booking_module',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='userpermissionset',
            name='loan_module',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='userpermissionset',
            name='party_type_module',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='userpermissionset',
            name='sr_module',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
